ALTER TABLE driver ADD COLUMN IF NOT EXISTS unit INT NOT NULL DEFAULT 0 AFTER name;
ALTER TABLE vehicle ADD COLUMN IF NOT EXISTS unit INT NOT NULL DEFAULT 0 AFTER canceled;

UPDATE driver SET unit = 0 WHERE unit IS NULL;
UPDATE vehicle SET unit = 0 WHERE unit IS NULL;
